version: '3'
services:
    nginx:
      image: nginx:latest
      ports:
        - 8090:80
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ../picoCTF:/var/www/html
      depends_on:
        - app
    app:
      build: ./
      volumes:
        - ../picoCTF:/var/www/html
        
    